version: "2"
run:
  modules-download-mode: vendor
  build-tags:
    - altinfra
    - containers_image_openpgp
    - exclude_graphdriver_devicemapper
    - exclude_graphdriver_btrfs
linters:
  default: none
  enable:
    - govet
    - musttag
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      dot-import-whitelist:
        - github.com/onsi/ginkgo
        - github.com/onsi/gomega
  exclusions:
    generated: disable
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: codec.BasicHandle is deprecated'
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/Azure/azure-sdk-for-go'
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - blank
        - dot
        - default
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - prefix(github.com/Azure)
        - prefix(github.com/openshift)
        - localmodule
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
