version: "2"
run:
  modules-download-mode: vendor
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      dot-import-whitelist:
        - github.com/onsi/ginkgo
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: codec.BasicHandle is deprecated'
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/Azure/azure-sdk-for-go'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
