// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/installer-aro-wrapper/pkg/util/azureclient/mgmt/compute (interfaces: ResourceSkusClient)

// Package mock_compute is a generated GoMock package.
package mock_compute

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	compute "github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute"
)

// MockResourceSkusClient is a mock of ResourceSkusClient interface.
type MockResourceSkusClient struct {
	ctrl     *gomock.Controller
	recorder *MockResourceSkusClientMockRecorder
}

// MockResourceSkusClientMockRecorder is the mock recorder for MockResourceSkusClient.
type MockResourceSkusClientMockRecorder struct {
	mock *MockResourceSkusClient
}

// NewMockResourceSkusClient creates a new mock instance.
func NewMockResourceSkusClient(ctrl *gomock.Controller) *MockResourceSkusClient {
	mock := &MockResourceSkusClient{ctrl: ctrl}
	mock.recorder = &MockResourceSkusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceSkusClient) EXPECT() *MockResourceSkusClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockResourceSkusClient) List(arg0 context.Context, arg1 string) ([]compute.ResourceSku, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]compute.ResourceSku)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockResourceSkusClientMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceSkusClient)(nil).List), arg0, arg1)
}
