module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.22.0

toolchain go1.24.8

require github.com/dmarkham/enumer v1.6.1

require (
	github.com/pascaldekloe/name v1.0.0 // indirect
	golang.org/x/mod v0.23.0 // indirect
	golang.org/x/sync v0.11.0 // indirect
	golang.org/x/tools v0.30.0 // indirect
)
