// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/installer-aro-wrapper/pkg/util/azureclient/mgmt/features (interfaces: DeploymentsClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../../util/mocks/azureclient/mgmt/features/features.go github.com/openshift/installer-aro-wrapper/pkg/util/azureclient/mgmt/features DeploymentsClient
//

// Package mock_features is a generated GoMock package.
package mock_features

import (
	context "context"
	reflect "reflect"

	features "github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-07-01/features"
	gomock "go.uber.org/mock/gomock"
)

// MockDeploymentsClient is a mock of DeploymentsClient interface.
type MockDeploymentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentsClientMockRecorder
	isgomock struct{}
}

// MockDeploymentsClientMockRecorder is the mock recorder for MockDeploymentsClient.
type MockDeploymentsClientMockRecorder struct {
	mock *MockDeploymentsClient
}

// NewMockDeploymentsClient creates a new mock instance.
func NewMockDeploymentsClient(ctrl *gomock.Controller) *MockDeploymentsClient {
	mock := &MockDeploymentsClient{ctrl: ctrl}
	mock.recorder = &MockDeploymentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentsClient) EXPECT() *MockDeploymentsClientMockRecorder {
	return m.recorder
}

// CreateOrUpdateAndWait mocks base method.
func (m *MockDeploymentsClient) CreateOrUpdateAndWait(ctx context.Context, resourceGroupName, deploymentName string, parameters features.Deployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateAndWait", ctx, resourceGroupName, deploymentName, parameters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateAndWait indicates an expected call of CreateOrUpdateAndWait.
func (mr *MockDeploymentsClientMockRecorder) CreateOrUpdateAndWait(ctx, resourceGroupName, deploymentName, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateAndWait", reflect.TypeOf((*MockDeploymentsClient)(nil).CreateOrUpdateAndWait), ctx, resourceGroupName, deploymentName, parameters)
}

// CreateOrUpdateAtSubscriptionScopeAndWait mocks base method.
func (m *MockDeploymentsClient) CreateOrUpdateAtSubscriptionScopeAndWait(ctx context.Context, deploymentName string, parameters features.Deployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateAtSubscriptionScopeAndWait", ctx, deploymentName, parameters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateAtSubscriptionScopeAndWait indicates an expected call of CreateOrUpdateAtSubscriptionScopeAndWait.
func (mr *MockDeploymentsClientMockRecorder) CreateOrUpdateAtSubscriptionScopeAndWait(ctx, deploymentName, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateAtSubscriptionScopeAndWait", reflect.TypeOf((*MockDeploymentsClient)(nil).CreateOrUpdateAtSubscriptionScopeAndWait), ctx, deploymentName, parameters)
}

// DeleteAndWait mocks base method.
func (m *MockDeploymentsClient) DeleteAndWait(ctx context.Context, resourceGroupName, deploymentName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndWait", ctx, resourceGroupName, deploymentName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAndWait indicates an expected call of DeleteAndWait.
func (mr *MockDeploymentsClientMockRecorder) DeleteAndWait(ctx, resourceGroupName, deploymentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndWait", reflect.TypeOf((*MockDeploymentsClient)(nil).DeleteAndWait), ctx, resourceGroupName, deploymentName)
}

// Get mocks base method.
func (m *MockDeploymentsClient) Get(ctx context.Context, resourceGroupName, deploymentName string) (features.DeploymentExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, deploymentName)
	ret0, _ := ret[0].(features.DeploymentExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeploymentsClientMockRecorder) Get(ctx, resourceGroupName, deploymentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeploymentsClient)(nil).Get), ctx, resourceGroupName, deploymentName)
}

// Wait mocks base method.
func (m *MockDeploymentsClient) Wait(ctx context.Context, resourceGroupName, deploymentName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx, resourceGroupName, deploymentName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockDeploymentsClientMockRecorder) Wait(ctx, resourceGroupName, deploymentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockDeploymentsClient)(nil).Wait), ctx, resourceGroupName, deploymentName)
}
